replicaCount: 1

image:
  repository: frontend-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: true                # set to true if you want to use Ingress
  annotations: {}
  hosts:
    - host: frontend.local     # the hostname you will use
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false               # leave false unless you configure HTTPRoute CRDs
